### ISSUE TITLE
did not install

### ISSUE THREAD

**Issue by fbaffie** [jmgnve/NVEDATA#3]
Here's the msg:
> install_github("jmgnve/NVEDATA")
Downloading GitHub repo jmgnve/NVEDATA@master
from URL https://api.github.com/repos/jmgnve/NVEDATA/zipball/master
Error in utils::unzip(src, list = TRUE) : 'exdir' does not exist

Is it your pb or mine?!

**Comment by jmgnve** [comment]
I restarted rstudio and afterwards it worked on my computer...

Try again!
