### ISSUE TITLE
better readme

### ISSUE THREAD

**Issue by honglioslo** [jmgnve/NVEDATA#7]
hva er "regine_main"?
Kan lege elev-band som para?

**Comment by jmgnve** [comment]
It is the same thing as station number (e.g. 2.11 etc).
Yes, you can add elev-band as a parameter.

Perhaps we should use a default value like this:

load_data_mean <- function(path_met, path_runoff, regine_main, time_vec, file_type, param = seq(-200,4000,200))

Then my scripts using this function don´t need to be changed, and people don´t need to add this parameter if they don´t like to.

I will check what regine, main, and so on means? And also look at the Norwegian names. We can add this to the readme.

**Comment by jmgnve** [comment]
Hong: do you want to try to add elev-band as a parameter? Or should I do it? It would be great if you could do it :)

**Comment by honglioslo** [comment]
I can do it and then I will have a better view of the structure and code. Could you please which files and where should I look at? Then I do not have to get lost i skogen :+1:

**Comment by jmgnve** [comment]
You need to do changes in file assemble_data in function from line 170 to 339. Look for lines with this code "breaks = seq(-200,4000,200)"

Thanks

**Comment by honglioslo** [comment]
change ele as par
You need to do changes in file assemble_data in function from line 170 to 339. Look for lines with this code "breaks = seq(-200,4000,200)"
